import {
	RiAlarmWarningLine,
	RiArrowDownSLine,
	RiArrowRightSLine,
	RiBardLine,
	RiBookLine,
	RiBookMarkedLine,
	RiCupLine,
	RiEarthLine,
	RiEyeCloseLine,
	RiEyeLine,
	RiFilmAiLine,
	RiBookOpenLine,
	RiChat1Line,
	RiCheckboxCircleLine,
	RiCloseLine,
	RiEarthLine,
	RiExternalLinkLine,
	RiEyeCloseLine,
	RiEyeLine,
	RiFileTextLine,
	RiHome2Line,
	RiLogoutBoxLine,
	RiMailLine,
	RiPhoneLine,
	RiPieChartLine,
	RiPlaneLine,
	RiPlantLine,
	RiRobot2Line,
	RiSearchLine,
	RiSettings3Line,
	RiTicketLine,
	RiTimeLine,
	RiUser2Line,
	RiVideoLine,
} from '@remixicon/react';

export const AristocratIcons = {
	Dashboard: RiHome2Line,
	Courses: RiBookMarkedLine,
	Attendees: RiRobot2Line,
	Metrics: RiPieChartLine,
	Documentation: RiBookLine,
	Community: RiEarthLine,
	HelpCenter: RiPlantLine,
	Settings: RiSettings3Line,
	Profile: RiUser2Line,
	Logout: RiLogoutBoxLine,
	Stars: RiBardLine,
	Eye: RiEyeLine,
	EyeClose: RiEyeCloseLine,
	Film: RiFilmAiLine,
	Cup: RiCupLine,
	Plane: RiPlaneLine,
	MessageCircle: RiChat1Line,
	Book: RiBookLine,
	Mail: RiMailLine,
	AlertCircle: RiAlarmWarningLine,
	BookOpen: RiBookOpenLine,
	CheckCircle: RiCheckboxCircleLine,
	ChevronDown: RiArrowDownSLine,
	ChevronRight: RiArrowRightSLine,
	Clock: RiTimeLine,
	ExternalLink: RiExternalLinkLine,
	FileText: RiFileTextLine,
	Phone: RiPhoneLine,
	Search: RiSearchLine,
	Ticket: RiTicketLine,
	Video: RiVideoLine,
	XCircle: RiCloseLine,
};
